### ISSUE TITLE
POST request without body

### ISSUE THREAD

**Issue by vierarb** [JCMais/node-libcurl#191] opened 2019-10-16 06:27 UTC
node-libcurl
`2.0.1`

cURL
`curl 7.65.3 (x86_64-apple-darwin18.7.0) libcurl/7.65.3 OpenSSL/1.1.1c zlib/1.2.11 brotli/1.0.7 c-ares/1.15.0 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.39.2`
`Release-Date: 2019-07-19`
`Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp`
`Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets`

When executing a `POST` request without `POSTFIELDS` (or with `POSTFIELDS` set to `''`), sometimes it's successful and returns the right response, but most of the times I'm getting this error:
`[Error: Server returned nothing (no headers, no data)]`.

It does not happen if I set the `POSTFIELDS` to `' '` or if I execute cURL from console, for example: `curl -L -X POST https://yahoo.com`.

Please, any clue about what's happening?

The code I'm using is the following:

```
const { Curl } = require('node-libcurl');

const curl = new Curl();

curl.setOpt(Curl.option.VERBOSE,          true);
curl.setOpt(Curl.option.USERAGENT,        'myuseragent');
curl.setOpt(Curl.option.DEFAULT_PROTOCOL, 'https');
curl.setOpt(Curl.option.PATH_AS_IS,       true);
curl.setOpt(Curl.option.URL,              'yahoo.com');
curl.setOpt(Curl.option.FOLLOWLOCATION,   true);
curl.setOpt(Curl.option.POSTREDIR,        0);
curl.setOpt(Curl.option.MAXREDIRS,        10)

curl.setOpt(Curl.option.POST,       1);
curl.setOpt(Curl.option.POSTFIELDS, '');

curl.on('end', function(statusCode, body, headers) {
  console.log(statusCode);

  this.close();
});

curl.on('error', function(error) {
  console.log(error);

  this.close();
});

curl.perform();
```

**Comment by JCMais** [comment] 2019-10-21 00:05
Looks like this has something to do with HTTP 2, if you disable it there are no errors. You can disable by forcing a specific version:
```
const { Curl, CurlHttpVersion } = require('node-libcurl');

// ...
curl.setOpt(Curl.option.HTTP_VERSION, CurlHttpVersion.V1_1);
// ...
```
 
Btw, can you force HTTP 2 by adding the flag `--http2` to the curl command and see if you can reproduce it in there too?

**Comment by JCMais** [comment] 2020-04-08 14:12
This was probably a bug with libcurl itself, the prerelease version of the addon available as `node-libcurl@next`, which uses libcurl 7.69.1, seems to work correctly. Please let me know if this is not the case.

This version will become `2.1.0` next week.

**Comment by JCMais** [comment] 2020-04-08 14:14
This was probably a bug with libcurl itself, the prerelease version of the addon available as node-libcurl@next, which uses libcurl 7.69.1, seems to work correctly. Please let me know if this is not the case.

This version will become 2.1.0 next week.

**Comment by vierarb** [comment] 2020-04-08 14:31
Thank you, will try.

**Comment by JCMais** [comment] 2020-04-12 16:57
I'm closing this as [v2.1.0](https://github.com/JCMais/node-libcurl/releases/tag/v2.1.0) (see the release page for full changelog) has been finally released. 🎉

If this is still an issue please let me know by reopening this issue.

**Closed by JCMais** 2020-04-12 16:57 UTC
Labels: bug
