### ISSUE TITLE
Using node-libcurl inside arm32v7 docker container fails with "out of memory" due to wrong package suggested in readme

### ISSUE THREAD

**Issue by mschrupp** [JCMais/node-libcurl#166] opened 2019-04-15 13:07 UTC
We have Dockerfile based on `arm32v7/node:10-slim`.

As mentioned in the `README.md`, we install `libcurl4-openssl-dev`.

The build works with it, but using `node-libcurl` to download file with _https_ fails with _out of memory_.

Installing `libcurl4-gnutls-dev` instead fixes the issue.

I don't know why the build works (?) though. I don't have the time to look into this any further, but I thought it might help somebody.

Maybe this could be mentioned in the `README.md`?

Thanks a lot for your work

**Comment by gsouf** [comment] 2019-04-30 09:37
I confirm that the above is the right fix for this issue

**Comment by JCMais** [comment] 2019-05-21 01:09
I can reproduce, I'm almost sure this has to do with the fact that Node.js 10 is built with OpenSSL 1.1.0, but on the image you mentioned libcurl is built with OpenSSL 1.0.0.

I've tried the image `arm32v7/node:8` and it does seem to work. The versions must match because Node.js itself also exports some OpenSSL symbols. I will investigate this further this week to make sure that is the problem.

**Comment by JCMais** [comment] 2019-05-25 20:45
Confirmed this is the issue, you must use a matching OpenSSL version to the one used by Node.js. Otherwise, you are going to get this error. The reason is the one I mentioned above, see issue here for more details https://github.com/JCMais/node-libcurl/issues/164.

So basically, you must rebuild libcurl with the OpenSSL version Node.js uses, or use other TLS backend, as you did.

There is a note about this on the `README` now: https://github.com/JCMais/node-libcurl#important-notes-on-prebuilt-binaries--direct-installation

**Closed by JCMais** 2019-05-25 20:45 UTC
Labels: *nix, arm, bug
