### ISSUE TITLE
Error: "Failed writing received data to disk/application"

### ISSUE THREAD

**Issue by druidvav** [JCMais/node-libcurl#193] opened 2019-10-24 13:23 UTC
Hello, here is reproducible example of an error with latest node-libcurl

```
const curl = new Curl();
curl.setOpt('URL', 'https://www.ponyexpress.ru/support/servisy-samoobsluzhivaniya/track/');
curl.setOpt(Curl.option.ACCEPT_ENCODING, 'gzip');
curl.on('end', function (statusCode, data, headers) {
    console.info(statusCode);
    console.info('---');
    console.log(data);
    console.info(data.length);
    console.info('---');
    console.info(this.getInfo('TOTAL_TIME'));
    this.close();
});
curl.on('error', (err) => {
    console.log(err);
    curl.close.bind(curl)
});
curl.perform();
```

**Comment by JCMais** [comment] 2019-10-27 21:52
Can reproduce, what was the OS and libcurl versions you were using @druidvav ?

**Comment by druidvav** [comment] 2019-10-27 21:57
Debian 9.11, libcurl4-nss-dev=7.52.1-5+deb9u9

**Comment by JCMais** [comment] 2019-10-27 22:08
If you are using the latest version of the addon, could you run `Curl.getVersionInfoString()` and post their results?

**Comment by druidvav** [comment] 2019-10-27 22:09
```
Version: libcurl/7.64.1 OpenSSL/1.1.1d zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.39.2
Protocols: dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Features: AsynchDNS, IDN, IPv6, Largefile, NTLM, NTLM_WB, SSL, libz, brotli, TLS-SRP, HTTP2, UnixSockets, HTTPS-proxy
[Error: Failed writing received data to disk/application]
```

**Comment by JCMais** [comment] 2019-12-10 01:31
I couldn't find the cause for this problem, any help is welcome.

**Comment by JCMais** [comment] 2020-04-07 21:58
This is still an issue. It only happens with gzip enabled, as it happens with curl itself I've opened an issue there: https://github.com/curl/curl/issues/5200

**Comment by JCMais** [comment] 2020-04-07 22:24
Closing this as it's in fact not a curl bug, but the server is returning a broken response. See linked issue above for more details.

**Closed by JCMais** 2020-04-07 22:24 UTC
Labels: bug, libcurl-only-related
