### ISSUE TITLE
pause/resume for pipe

### ISSUE THREAD

**Issue by ronag** [JCMais/node-libcurl#172] opened 2019-05-14 18:19 UTC
I'm trying to implement a simple pipe again regular node streams... However, I'm a bit unsure how to achieve the pause/resume?

I've tried using the `pause` with the different flags however they seem to get stuck at some point... 

Could we maybe add the standard node protocol of `pause, resume`?

**Comment by JCMais** [comment] 2019-05-16 15:28
Could you post a code that reproduces the scenario where it gets stuck?

I have no plans to implement streams right now, it would be great to have but I have no time right now.

**Comment by ovx** [comment] 2019-05-26 20:19
Hi, I'm having a similar problem (or related to the pause function), there are two weird things happening:

1. if you return `CURL_READFUNC_PAUSE` in `READFUNCTION` for the second time, resume using `.pause(0)` no longer works (doesn't resume the reading)
2. if you resume using `.pause(0)` after a longer delay (>= 1s) it doesn't work even for the first time (to test this, just change `const TIMEOUT` to `1000`)

libcurl version 1.3.3, node 10.13

Test code:

```js
const { Curl }  = require('node-libcurl');

const CURL_READFUNC_PAUSE = 0x10000001;
const TIMEOUT = 100;

const curl = new Curl();

curl.setOpt('CUSTOMREQUEST', 'POST');
curl.setOpt('URL', 'https://httpbin.org/anything');
// curl.setOpt('VERBOSE', true);
curl.setOpt('UPLOAD', true);

let count = -1;
curl.setOpt('READFUNCTION', (buf, size, nmemb) => {
  count += 1;

  if (count === 0) {
    console.log('> WRITE', count);
    return buf.write('chunk' + count);

  } else if (count === 1) {
    console.log('> PAUSE');
    setTimeout(() => {
      curl.pause(0);
    }, TIMEOUT);
    return CURL_READFUNC_PAUSE;

  } else if (count === 2) {
    console.log('> WRITE', count);
    return buf.write('chunk' + count);

  } else if (count === 3) {
    console.log('> PAUSE');
    setTimeout(() => {
      curl.pause(0);
    }, TIMEOUT);
    return CURL_READFUNC_PAUSE;

  } else if (count === 4) {
    console.log('> WRITE', count);
    return buf.write('chunk' + count);

  } else {
    console.log('> END', count);
    return 0;
  }
});

curl.on('end', function (statusCode, data, headers) {
  console.info(statusCode);  
  this.close();
});

curl.on('error', curl.close.bind(curl));
curl.perform();

```

**Comment by JCMais** [comment] 2019-05-27 13:42
@ovx  thanks for the code!

Which libcurl version are you using? You can get that calling `Curl.getVersion()`.

I could reproduce the issue on `1.3.3` with libcurl `7.58`. Can you check if it works with the pre-release version of the addon? It's available as `node-libcurl@next`. 

Note that there are some breaking changes, here is the above code made to work with it:
```
const { Curl, CurlReadFunc } = require('node-libcurl')

const TIMEOUT = 3000

const curl = new Curl()
console.log(Curl.getVersion())

curl.setOpt('CUSTOMREQUEST', 'POST')
curl.setOpt('URL', 'https://httpbin.org/anything')
curl.setOpt('VERBOSE', true)
curl.setOpt('UPLOAD', true)

let count = -1

curl.setOpt('READFUNCTION', (buf, size, nmemb) => {
  count += 1

  if (count === 0) {
    console.log('> WRITE', count)
    return buf.write('chunk' + count)
  } else if (count === 1) {
    console.log('> PAUSE')
    setTimeout(() => {
      curl.pause(0)
    }, TIMEOUT)
    return CurlReadFunc.Pause
  } else if (count === 2) {
    console.log('> WRITE', count)
    return buf.write('chunk' + count)
  } else if (count === 3) {
    console.log('> PAUSE')
    setTimeout(() => {
      curl.pause(0)
    }, TIMEOUT)
    return CurlReadFunc.Pause
  } else if (count === 4) {
    console.log('> WRITE', count)
    return buf.write('chunk' + count)
  } else {
    console.log('> END', count)
    return 0
  }
})

curl.on('end', function (statusCode, data, headers) {
  console.info(statusCode)
  this.close()
})

curl.on('error', function (error) {
  console.log(error)
  this.close()
})
curl.perform()
```

It worked correctly here:
```
➜ node issue-172.js
libcurl/7.65.0 OpenSSL/1.1.0i zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.8.2 nghttp2/1.34.0
> WRITE 0
> PAUSE
> WRITE 2
> PAUSE
> WRITE 4
> END 5
200
```

**Comment by ovx** [comment] 2019-05-27 18:13
Tested with @next version and it works fine. Thanks!

The previous version: libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1 (on MacOS)

**Comment by JCMais** [comment] 2019-05-27 18:34
Great to hear, closing this as it's fixed on `node-libcurl@next`. I'm looking to release it as v2 this weekend, I was postponing it because I wanted to get some API docs going, but I will release without it, atleast for now. The examples should be sufficient to document the existing API.

**Closed by JCMais** 2019-05-27 18:34 UTC
