### ISSUE TITLE
unable to npm install

### ISSUE THREAD

**Issue by philipheinser** [JCMais/node-libcurl#395] opened 2023-10-02 17:28 UTC
```
error /Users/1234/apps/some-graphql/node_modules/node-libcurl: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/1234/apps/some-graphql/node_modules/node-libcurl
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.10
node-pre-gyp info using node@20.8.0 | darwin | arm64
node-pre-gyp info check checked for "/Users/1234/apps/some-graphql/node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)
node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v3.0.0/node_libcurl-v3.0.0-node-v115-darwin-arm64-unknown.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/JCMais/node-libcurl/releases/download/v3.0.0/node_libcurl-v3.0.0-node-v115-darwin-arm64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for node-libcurl@3.0.0 and node@20.8.0 (node-v115 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/JCMais/node-libcurl/releases/download/v3.0.0/node_libcurl-v3.0.0-node-v115-darwin-arm64-unknown.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.0
gyp info using node@20.8.0 | darwin | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.0
gyp info using node@20.8.0 | darwin | arm64
gyp info find Python using Python version 3.11.5 found at "/opt/homebrew/opt/python@3.11/bin/python3.11"
gyp info spawn /opt/homebrew/opt/python@3.11/bin/python3.11
gyp info spawn args [
gyp info spawn args   '/Users/1234/apps/some-graphql/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/1234/apps/some-graphql/node_modules/node-libcurl/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/1234/apps/some-graphql/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/1234/Library/Caches/node-gyp/20.8.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/1234/Library/Caches/node-gyp/20.8.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/1234/apps/some-graphql/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/1234/Library/Caches/node-gyp/20.8.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/1234/apps/some-graphql/node_modules/node-libcurl',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /usr/lib/libcurl.dylib (No such file or directory)
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.0
gyp info using node@20.8.0 | darwin | arm64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
clang: error: no such file or directory: '/usr/include'
make: *** [Release/obj.target/node_libcurl/src/node_libcurl.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/1234/apps/some-graphql/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Darwin 23.0.0
gyp ERR! command "/opt/homebrew/Cellar/node/20.8.0/bin/node" "/Users/1234/apps/some-graphql/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/1234/apps/some-graphql/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/Users/1234/apps/some-graphql/node_modules/node-libcurl/lib/binding" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v115"
gyp ERR! cwd /Users/1234/apps/some-graphql/node_modules/node-libcurl
gyp ERR! node -v v20.8.0
gyp ERR! node-gyp -v v9.3.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/homebrew/Cellar/node/20.8.0/bin/node /Users/1234/apps/some-graphql/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/1234/apps/some-graphql/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/Users/1234/apps/some-graphql/node_modules/node-libcurl/lib/binding --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/1234/apps/some-graphql/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
node-pre-gyp ERR! System Darwin 23.0.0
node-pre-gyp ERR! command "/opt/homebrew/Cellar/node/20.8.0/bin/node" "/Users/1234/apps/some-graphql/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/1234/apps/some-graphql/node_modules/node-libcurl
node-pre-gyp ERR! node -v v20.8.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.10
node-pre-gyp ERR! not ok 
```

**Comment by SudoVanilla** [comment] 2023-10-05 01:08
According to this log, `/usr/lib/libcurl.dylib` is not found, meaning that its required by node-libcurl.

Is libcurl installed on your machine?

**Comment by nktnet1** [comment] 2023-10-17 05:16
See here for a workaround relating to downgrading node:
- https://github.com/JCMais/node-libcurl/issues/396#issuecomment-1762624778

**Comment by JCMais** [comment] 2023-10-30 21:41
this is the same as https://github.com/JCMais/node-libcurl/issues/399, closing as a duplicate of it

**Closed by JCMais** 2023-10-30 21:41 UTC
Labels: bug, triage
