### ISSUE TITLE
[feat] rewrite `node-libcurl` with, the **ONLY** isomorphic way, napi

### ISSUE THREAD

**Issue by loynoir** [JCMais/node-libcurl#389] opened 2023-07-14 01:33 UTC
`napi` seems is the **ONLY** isomorphic js way to use libcurl

- `deno` napi since [pull/13633](https://github.com/denoland/deno/pull/13633), stable at [v1.31](https://deno.com/blog/v1.31#stabilization-of-node-api)

- `bun` is also [implementing](https://github.com/oven-sh/bun/issues/158) napi

Related issue

- https://github.com/JCMais/node-libcurl/issues/387

- https://github.com/denoland/deno/issues/17910

- https://github.com/denoland/deno/issues/8821

**Comment by JCMais** [comment] 2023-08-18 16:10
duplicate of https://github.com/JCMais/node-libcurl/issues/155

unfortunately I do not have enough bandwidth to work on this atm

**Closed by JCMais** 2023-08-18 16:10 UTC
