### ISSUE TITLE
Updating libcurl to 7.40

### ISSUE THREAD

**Issue by kevinhikaruevans** [JCMais/node-libcurl#8] opened 2015-02-09 22:01 UTC
Would it be possible to update libcurl to 7.40?

**Comment by JCMais** [comment] 2015-02-09 22:24
Yes, I'm already working on that, keep an eye on https://github.com/JCMais/curl-for-windows, It's probably going to be updated this weekend or middle of next week.

I'm closing this since it's specific to the windows dependency.

**Closed by JCMais** 2015-02-09 22:24 UTC

**Comment by JCMais** [comment] 2015-03-05 21:44
@kevinhikaruevans I didn't forgot about this issue, the problem is that libcurl had a bug on windows with version 7.40 and openssl, it was fixed today: http://sourceforge.net/p/curl/bugs/1488/

There is still an (issue open)[http://sourceforge.net/p/curl/bugs/1484/] that can cause some trouble to people using Windows, but I've already updated the repository.

Now I just need to implement new options that were added with the new version, check the issue https://github.com/JCMais/node-libcurl/issues/12
