### ISSUE TITLE
curl callback not fired on Electron 13

### ISSUE THREAD

**Issue by FandyTADA** [JCMais/node-libcurl#306] opened 2021-08-18 08:35 UTC
i have a strange issue running curl on Electron 13.  This is my curl version:

**libcurl version:**
libcurl/7.78.0 (SecureTransport) OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.9.0 nghttp2/1.44.0 librtmp/2.3 OpenLDAP/2.5.6

**Node version:**
v14.17.5

node-libcurl was built using electron-rebuild using cp++17.

```
const curl = new Curl();

curl.setOpt(Curl.option.URL, 'https://www.google.com');
curl.setOpt(Curl.option.FOLLOWLOCATION, true);
curl.setOpt(Curl.option.VERBOSE, true);

curl.on('end', (statusCode, body, headers, curlInstance) => {
  console.info('Status Code: ', statusCode);
  console.info('Headers: ', headers);
  console.info('Body length: ', body.length);

  // always close the `Curl` instance when you don't need it anymore
  // Keep in mind we can do multiple requests with the same `Curl` instance
  // before it's closed, we just need to set new options if needed
  // and call `.perform()` again.
  curlInstance.close();
});

// Error will be a JS error, errorCode will be the raw error code (as int) returned from libcurl
curl.on('error', (error, errorCode, curlInstance) => {
  curlInstance.close();
});

curl.perform();
```

`curl.on('end'` is never called.

However, i tried adding fake http request to localhost using `node https` before executing `curl`

```
try {
  https.request({ hostname: 'localhost' });
} catch (error) {}

const curl = new Curl();

curl.setOpt(Curl.option.URL, 'https://www.google.com');
curl.setOpt(Curl.option.FOLLOWLOCATION, true);
curl.setOpt(Curl.option.VERBOSE, true);

curl.on('end', (statusCode, body, headers, curlInstance) => {
  console.info('Status Code: ', statusCode);
  console.info('Headers: ', headers);
  console.info('Body length: ', body.length);

  // always close the `Curl` instance when you don't need it anymore  
  // Keep in mind we can do multiple requests with the same `Curl` instance
  // before it's closed, we just need to set new options if needed
  // and call `.perform()` again.
  curlInstance.close();
});

// Error will be a JS error, errorCode will be the raw error code (as int) returned from libcurl
curl.on('error', (error, errorCode, curlInstance) => {
  curlInstance.close();
});

curl.perform();
```

after adding `https.request` the curl callback is being called successfully.

**Comment by FandyTADA** [comment] 2021-08-19 06:28
Update: using `Easy` with parameter `Curl.option.WRITEFUNCTION` work properly, buffer is being received.  so my assumption the issue is in eventemitter

**Comment by JCMais** [comment] 2022-02-12 12:52
When I tried this I was not able to reproduce it with Electron, if you could provide a sample code that reproduces the issue that would be great.

**Comment by JCMais** [comment] 2024-02-13 21:20
To keep the maintainability of this project, I am closing old tickets (sorry if your ticket was kept open for so long without feedback). 

If the issue continues with the latest version of node-libcurl, please feel free to create a new ticket.

**Closed by JCMais** 2024-02-13 21:20 UTC
Labels: bug, cannot-reproduce
