### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by algv** [JCMais/node-libcurl#241] opened 2020-07-29 12:39 UTC
"JavaScript heap out of memory" for POST large files. Example:

```js
const fs = require('fs')
const { Curl } = require('../dist')
const curl = new Curl()
const url = 'http://httpbin.org/post'
const link = '/home/test/file_500mb' // 500MB file

const data = fs.readFileSync(link)

curl.setOpt(Curl.option.URL, url)
curl.setOpt(Curl.option.POSTFIELDS, JSON.stringify({ data }))
curl.setOpt(Curl.option.VERBOSE, true)
curl.on('end', (statusCode, body) => {
  console.log(statusCode)

  console.log('Body received from httpbin:')

  curl.close()
})

curl.on('error', curl.close.bind(curl))

curl.perform()

```

Out:

> 
> <--- Last few GCs --->
> [18088:0x4166ec0]      315 ms: Mark-sweep 8.6 (13.7) -> 7.8 (17.7) MB, 3.0 / 0.0 ms  (+ 1.1 ms in 6 steps since start of marking, biggest step 0.6 ms, walltime since start of marking 223 ms) (average mu = 1.000, current mu = 1.000) finalize incremental ma[18088:0x4166ec0]      763 ms: Mark-sweep 193.8 (203.8) -> 182.5 (191.7) MB, 0.9 / 0.0 ms  (+ 0.3 ms in 3 steps since start of marking, biggest step 0.3 ms, walltime since start of marking 377 ms) (average mu = 0.997, current mu = 0.997) finalize incremen
> <--- JS stacktrace --->
> ==== JS stack trace =========================================
> 0: ExitFrame [pc: 0x13cce79]
> Security context: 0x2946269808d1 
> 1: toJSON [0x2965209b1761] [buffer.js:~1079] [pc=0x3489221449d5](this=0x005caec3d909 )
> 2: arguments adaptor frame: 1->0
> 3: InternalFrame [pc: 0x134fd9d]
> 4: EntryFrame [pc: 0x134fb78]
> 5: builtin exit frame: stringify(this=0x29462699ee79 ,0x1fcd6aa804b1 ,0x1fcd6aa804b1 <und...
> FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory
> 1: 0xa0bb60 node::Abort() [node]
> 2: 0xa0bf6c node::OnFatalError(char const*, char const*) [node]
> 3: 0xb820fe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
> 4: 0xb82479 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
> 5: 0xd2ee35  [node]
> 6: 0xf2293a v8::internal::HashTable<v8::internal::NumberDictionary, v8::internal::NumberDictionaryShape>::New(v8::internal::Isolate*, int, v8::internal::AllocationType, v8::internal::MinimumCapacity) [node]
> 7: 0xf2307b v8::internal::HashTable<v8::internal::NumberDictionary, v8::internal::NumberDictionaryShape>::EnsureCapacity(v8::internal::Isolate*, v8::internal::Handlev8::internal::NumberDictionary, int, v8::internal::AllocationType) [node]
> 8: 0xf2359a v8::internal::Dictionary<v8::internal::NumberDictionary, v8::internal::NumberDictionaryShape>::Add(v8::internal::Isolate*, v8::internal::Handlev8::internal::NumberDictionary, unsigned int, v8::internal::Handlev8::internal::Object, v8::internal::PropertyDetails, int*) [node]
> 9: 0xe748be  [node]
> 10: 0xeddb32 v8::internal::JSObject::AddDataElement(v8::internal::Handlev8::internal::JSObject, unsigned int, v8::internal::Handlev8::internal::Object, v8::internal::PropertyAttributes) [node]
> 11: 0xf297fa v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handlev8::internal::Object, v8::internal::PropertyAttributes, v8::Maybev8::internal::ShouldThrow, v8::internal::StoreOrigin) [node]
> 12: 0xf2a537 v8::internal::Object::SetProperty(v8::internal::LookupIterator*, v8::internal::Handlev8::internal::Object, v8::internal::StoreOrigin, v8::Maybev8::internal::ShouldThrow) [node]
> 13: 0x105eaf4 v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handlev8::internal::Object, v8::internal::Handlev8::internal::Object, v8::internal::Handlev8::internal::Object, v8::internal::StoreOrigin, v8::Maybev8::internal::ShouldThrow) [node]
> 14: 0xdbf71a v8::internal::Runtime_KeyedStoreIC_Slow(int, unsigned long*, v8::internal::Isolate*) [node]
> 15: 0x13cce79  [node]
> 

**If use other test, with Buffer:**

```js
const fs = require('fs')
const v8 = require('v8')
const { Curl } = require('../dist')
const curl = new Curl()
const buffer = Buffer.alloc(1 * 1024 * 1024 * 1000 - 1, '1') // ~1GB
const data = buffer.toString()
const url = 'http://httpbin.org/post'

curl.setOpt(Curl.option.URL, url)
curl.setOpt(Curl.option.POSTFIELDS, JSON.stringify({ data }))
curl.setOpt(Curl.option.VERBOSE, true)
curl.on('end', (statusCode, body) => {
  console.log(statusCode)

  console.log('Body received from httpbin:')

  curl.close()
})

curl.on('error', curl.close.bind(curl))

curl.perform()

```

Out:

> node: ../node_modules/nan/nan.h:1140: Nan::Utf8String::Utf8String(v8::Localv8::Value): Assertion `len <= 2147483647' failed.

ubuntu 19.10 , node 12.18.2

**Comment by JCMais** [comment] 2020-07-29 13:30
For upload large files you have a few options:
Use `CURLOPT_HTTPPOST`, which allows for multipart/form-data uploads, example here: https://github.com/JCMais/node-libcurl/blob/develop/examples/08-file-upload-post.js

Use [`CURLOPT_READFUNCTION`](https://curl.haxx.se/libcurl/c/CURLOPT_READFUNCTION.html) option with the [`CURLOPT_POST`](https://curl.haxx.se/libcurl/c/CURLOPT_POST.html) enabled, this will allow you to read the file in chunks. There is an example (for PUT, but the idea is the same) here: https://github.com/JCMais/node-libcurl/blob/develop/examples/08-file-upload-stream.js

**Comment by algv** [comment] 2020-07-31 06:20
CURLOPT HTTP POST and CURLOPT_READFUNCTION work, thanks. Are you have idea, how catch memory allocation (heap size) problem?

**Comment by JCMais** [comment] 2020-07-31 11:58
If you mean catching the error so that it does not kill the Node.js process, I don't think there is an easy way to do that.


Closing as the issue is fixed.

**Closed by JCMais** 2020-07-31 11:58 UTC
