### ISSUE TITLE
Getting error while using Node v4.2.4

### ISSUE THREAD

**Issue by trangiiee** [JCMais/node-libcurl#43] opened 2016-01-06 17:08 UTC
Hello~

Could you help me diagnose my error? Everything was working fine when I was using Node v 0.12.7.

```
return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen(/Users/angie/projects/node-projects/search-api/node_modules/node-libcurl/lib/binding/node_libcurl.node, 1): Library not loaded: /Users/travis/lib/libcurl.4.dylib
  Referenced from: /Users/angie/projects/node-projects/search-api/node_modules/node-libcurl/lib/binding/node_libcurl.node
  Reason: Incompatible library version: node_libcurl.node requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0
```

OS: OSX 10.10.5
xcode: 7.2
libcurl: 7.43.0

Thanks!

**Comment by JCMais** [comment] 2016-01-06 20:44
Which version of the addon are you using?

**Comment by trangiiee** [comment] 2016-01-06 20:47
which version of node-libcurl am I using? 0.7.0

**Comment by JCMais** [comment] 2016-01-06 20:50
When you updated node.js, did you rebuilt the module? (aka, ``npm install node-libcurl``)

If yes, try running ``npm install node-libcurl --build-from-source``.

I don't have a Mac to test it, but looks like an issue with homebrew from what I can see searching for this error, can you try to update libcurl/homebrew?

**Comment by trangiiee** [comment] 2016-01-07 13:06
I didn't have homebrew on the computer I'm working in so i installed it and now i have libcurl v7.46.0

running `node .` i get a different error: 

```
module.js:460
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/angie/projects/node/search-api/node_modules/node-libcurl/lib/Curl.js:27:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

I also tried running tried running `npm install node-libcurl --build-from-source` and I get this error: 

```
npm WARN enoent ENOENT, open '/Users/angie/projects/node/search-api/node_modules/bin/package.json'
npm WARN enoent ENOENT, open '/Users/angie/projects/node/search-api/node_modules/etc/package.json'
npm WARN enoent ENOENT, open '/Users/angie/projects/node/search-api/node_modules/lib/package.json'
npm WARN search-api@1.0.0 No license field.
npm ERR! Darwin 15.2.0
npm ERR! argv "node" "/Users/angie/projects/node/search-api/node_modules/.bin/npm" "install" "node-libcurl" "--build-from-source"
npm ERR! node v0.12.7
npm ERR! npm  v3.5.2
npm ERR! path /Users/angie/projects/node/search-api/node_modules/.staging/abbrev-ad080861
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, rename '/Users/angie/projects/node/search-api/node_modules/.staging/abbrev-ad080861'
npm ERR! enoent ENOENT, rename '/Users/angie/projects/node/search-api/node_modules/.staging/abbrev-ad080861'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/angie/projects/node/search-api/npm-debug.log
```

Thank you so much for helping me!

**Comment by JCMais** [comment] 2016-01-07 13:50
Looks like an issue with npm, try cleaning the cache and reinstalling the node modules:

```bash
$ npm clean cache
$ rm -rf node_modules
```

**Comment by trangiiee** [comment] 2016-01-07 14:10
yay! 

That did the trick. 

Thank you so much! 

Btw, for reference the first command needs to be switched around to be `$ npm cache clean`

**Comment by JCMais** [comment] 2016-01-07 14:14
Glad you got it fixed!

**Comment by YoshProgrammer** [comment] 2016-02-04 20:25
@JCMais  I'm experiencing this issue as well...

I have libcurl 7.43.0 and followed these same commands as you instructed. Even clearing the cache, deleting node_modules and rebuilding them.


```
module.js:435
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen(/Users/jbrown/Documents/projects/Weebly-API/node_modules/node-libcurl/lib/binding/node_libcurl.node, 1): Library not loaded: /Users/travis/lib/libcurl.4.dylib
  Referenced from: /Users/jbrown/Documents/projects/Weebly-API/node_modules/node-libcurl/lib/binding/node_libcurl.node
  Reason: Incompatible library version: node_libcurl.node requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/jbrown/Documents/projects/Weebly-API/node_modules/node-libcurl/lib/Easy.js:38:29)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/jbrown/Documents/projects/Weebly-API/node_modules/node-libcurl/index.js:1:74)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by JCMais** [comment] 2016-02-04 20:42
This is an issue with the libcurl version installed, it wants compatibility with library version 4 (Which probably means Mac 10.4), but this module only supports 9 (Mavericks, 10.9) or later.

I really don't know how to fix this since I don't own a Mac, but from what I could gather doing some research you can try to install homebrew which has a libcurl version compiled with the latest xcode.

**Comment by YoshProgrammer** [comment] 2016-02-04 20:43
Interesting cause I'm running 10.10.5
I'll see if I can get it to work, otherwise I'll switch to laravel framework for the project im trying to do.

thanks

**Comment by YoshProgrammer** [comment] 2016-02-04 20:44
Yeah I'm already running Homebrew and installed latest curl + libcurl so just an odd error. Bummer, was hoping this library would work for me.

Thanks anyways

**Comment by JCMais** [comment] 2016-02-04 20:44
The Mac version you have installed is not the cause, but the minimum version required by the libcurl module (not this addon). This is set while compiling it.

**Comment by YoshProgrammer** [comment] 2016-02-04 20:45
ahh I see, the libcurl itself is saying hey I need compatibility with 4 but this module is 9+

**Comment by JCMais** [comment] 2016-02-04 21:07
yup, the easy way to fix that is you getting libcurl and compiling it from source, if you have the time to do that, it would be like the following:

``
$ cd ~
$ git clone https://github.com/curl/curl.git --single-branch --branch=curl-7_47_0 && cd curl
$ git checkout curl-7_47_0
$ export MACOSX_DEPLOYMENT_TARGET="10.8"
$ export PATH=$PATH:~/curl-binaries
$ ./configure --prefix=~/curl-binaries --with-darwinssl --disable-shared --enable-static
$ make && make install
$ npm install node-libcurl --build-from-source
``

**Comment by JCMais** [comment] 2016-02-04 21:08
yup, the easy way to fix that is you getting libcurl and compiling it from source, if you have the time to do that, it would be like the following:

```
$ cd ~
$ git clone https://github.com/curl/curl.git --single-branch --branch=curl-7_47_0 && cd curl
$ git checkout curl-7_47_0
$ export MACOSX_DEPLOYMENT_TARGET="10.8"
$ export PATH=$PATH:~/curl-binaries
$ ./configure --prefix=~/curl-binaries --with-darwinssl --disable-shared --enable-static
$ make && make install
$ npm install node-libcurl --build-from-source
```

**Comment by YoshProgrammer** [comment] 2016-02-04 23:05
@JCMais i'll try that, i'd rather avoid losing some of the node work i've done so far for this project

**Comment by YoshProgrammer** [comment] 2016-02-04 23:48
@JCMais running into a snag, it doesn't appear there is a configure file or directory when getting to that step, i've googled but not much help so far. Any pointers on what that means/why it's saying no such file or dir?

**Comment by JCMais** [comment] 2016-02-04 23:52
I've missed the call to ``./buildconf`` before the ``.\configure``.

Ping me on gitter if you other issues.

**Comment by YoshProgrammer** [comment] 2016-02-04 23:52
Will do thanks for going above and beyond on this!

**Comment by kohanyirobert** [comment] 2016-02-27 17:26
Sorry updating a closed issue, but I was having the same problem and I was able to solve it without building manually anything.

I just removed the module `npm uninstall node-libcurl` then installed it like this `npm install node-libcurl --build-from-source` after that I saw the following
```
> node-pre-gyp install --fallback-to-build

  CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
  CXX(target) Release/obj.target/node_libcurl/src/Easy.o
  CXX(target) Release/obj.target/node_libcurl/src/Share.o
  CXX(target) Release/obj.target/node_libcurl/src/Multi.o
  ...
```
and then it was working. If I just installed it with `npm install node-libcurl` the following was logged
```
> node-libcurl@0.8.0 install /Users/.../node_modules/node-libcurl
> node-pre-gyp install --fallback-to-build

[node-libcurl] Success: "/Users/.../node_modules/node-libcurl/lib/binding/node_libcurl.node" is installed via remote
```
I don't know what *installed via remote* means, but essentially it didn't work that way, only if the library is built locally.

**Comment by JCMais** [comment] 2016-02-27 22:53
> I don't know what installed via remote means

It means that one pre built binary for your system was found, however you are probably getting one error when trying to use the library because it was compiled with one more recent toolchain, that your system currently doesn't have, that is why it works when you use --build-from-source, because it ignores the prebuilt binaries and just build it directly, using the toolchain you currently have.

**Comment by zyvas** [comment] 2016-04-13 07:33
The main reason for this is that there is no `node-pre-gyp` installed, Is not it ?
why not try it in `package.json` . like [this](https://github.com/mapbox/node-pre-gyp#configuring)
```
"scripts": {
    "preinstall": "npm install node-pre-gyp",
    "install": "node-pre-gyp install --fallback-to-build",
    "test": "mocha test --reporter spec",
    "docs": "jsdoc2md lib/*.js > api.md"
  },
```

**Comment by sridharspeaks** [comment] 2016-11-23 22:40
@kohanyirobert thank you, your solution simply worked for me.

**Comment by simiansim** [comment] 2017-09-03 00:46
Just pointing this out that all of these people reported exactly "Library not loaded: /Users/travis/lib/libcurl.4.dylib", and I don't think any of those people are named "travis". This is a baked-in incorrect reference.

The compiled file "node_modules/node-libcurl/lib/binding/node_libcurl.node" contains this reference (BTW: the "Users/travis" directory does not exist on my machine either, in case that was a surprise). The fact that this actually works for most people on a Mac seems very accidental (It fails trying an invalid ref before trying other system paths).

Once rebuilt with the commands described above there is no such reference at all ("travis" or otherwise), in the binding file.

**Comment by Meabed** [comment] 2017-09-27 18:05
@simiansim 
you are right, i have installed
```
npm install node-pre-gyp -g
npm install node-libcurl --build-from-source --fallback-to-build
```

and it works just fine, i am sure this travis issue is something but the message displayed is wrong maybe.

**Comment by peterruijter** [comment] 2017-10-19 14:14
Sorry for commenting on this closed issue, but what helped me to solve this problem is: 
`brew update && brew upgrade`  and lastly `brew reinstall curl`

The suggested solution that @JCMais gave on 4 Feb 2016, does not create or replace the libcurl.4.dylib file what the source of the problem is and where the compiler is complaining about.

I hope this solution will work for someone else too...

**Comment by simiansim** [comment] 2017-10-25 06:19
What you are doing by running brew is to separately install curl and ensure that libcurl.4.dylib is "somewhere" on your system path & it only works if the place that brew installs it is also on your system path. While I am not sure, I suspect (hope) that @JCMais is updating the build automation (travis) that creates the bindings so that you don't have to fix it externally.

**Comment by JCMais** [comment] 2017-10-25 11:50
I'm keeping an eye on this issue, but currently I'm not having time to work on it, if anyone has the opportunity and know-how to fix it, it would be awesome.

**Comment by JCMais** [comment] 2018-08-17 12:49
reopening this since it's still an issue.

For a matter of fact, there is travis on the patch of the linked library because the process of generating macOS prebuilt binaries is by building the library in a macOS environment on Travis CI, the build config is here if anyone can take a look: https://github.com/JCMais/node-libcurl/blob/84006ec/.travis.yml

**Comment by koskokos2** [comment] 2018-08-17 17:38
Full path should be replaced with @rpath and rpaths added for mac, so basically after node_libcurl.node is built we need to execute:

`install_name_tool -change /Users/travis/lib/libcurl.4.dylib @rpath/libcurl.4.dylib node_libcurl.node
install_name_tool -add_rpath /opt/local/lib node_libcurl.node
install_name_tool -add_rpath /usr/lib node_libcurl.node
`

**Comment by koskokos2** [comment] 2018-08-19 09:38
I submitted changes to binding.gyp that will fix this issue. They make output of "otool -L" look way better and "otool -l" has standard paths to libs on mac.
`otool -L lib/binding/node_libcurl.node
lib/binding/node_libcurl.node:
        @rpath/libcurl.dylib (compatibility version 10.0.0, current version 10.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
`

**Comment by berstend** [comment] 2018-08-20 18:03
Ran into the same issue today:

```
 Reason: Incompatible library version: node_libcurl.node requires version 10.0.0 or later, but libcurl.4.dylib provides version 7.0.0
```

Switched to @koskokos2's branch (thanks!) and everything is super now 🎉:

```bash
yarn add koskokos2/node-libcurl#linking-improvement-mac
```

```js
console.log(require('node-libcurl').Curl.getVersion())
// => libcurl/7.43.0 SecureTransport zlib/1.2.5
```

**Comment by koskokos2** [comment] 2018-08-20 18:14
I added one more path that will handle Brew when does not want to mess with system curl and is using special path. Now I think it is ready to be merged.

**Comment by simiansim** [comment] 2018-08-21 03:16
LGTM too.

**Closed** 2018-08-25 16:56 UTC
Labels: build-error, darwin

**Comment by pietermees** [comment] 2018-09-06 17:44
@JCMais worked for me!
