### ISSUE TITLE
`zstd` dependency is missing

### ISSUE THREAD

**Issue by dr-dimitru** [JCMais/node-libcurl#274] opened 2021-02-06 21:08 UTC
### Error:

```
Error: dlopen(node_modules/node-libcurl/lib/binding/node_libcurl.node, 1): Library not loaded: /usr/local/opt/zstd/lib/libzstd.1.dylib
Referenced from: node_modules/node-libcurl/lib/binding/node_libcurl.node

Reason: image not found
  at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
  at Module.load (internal/modules/cjs/loader.js:863:32)
```

### Hot Fix

Install `zstd` package

This issue took at least 8 hour from our team 😅
Added 🔥 hotfix instruction to library where `node-libcurl` is dependency — https://github.com/VeliovGroup/request-extra#3-missing-libraries

@JCMais `node-libcurl` expect to have `zstd` library installed? Or it's a bug and dependency is missing?

Tested on `macOS@10.12.6` and `macOS@10.15`, `node@12.18.4` and `node@14.15.4`, `npm@6.14.8` and `npm@7.5.2`.

**Comment by JCMais** [comment] 2021-02-13 19:06
Hi @dr-dimitru, sorry if this took some time to debug, I have to take a look at the way the addon is being built in macOS, as it should not really require external dependencies, as it should be built statically with all the dependencies.

Unfortunately, I'm not able to that at the moment as I do not have a mac available. I should get around by the end of the month. Until then I will keep this issue opened.

**Comment by dr-dimitru** [comment] 2021-02-13 19:15
@JCMais got it, this is not only me, a lot of users of the library where node-libcurl used as dependency were affected. So maybe this is a clue -- only when it's used as dependency of the other package.

Had to add different tips and tricks to "known issues" section here -- https://www.npmjs.com/package/request-libcurl

**Comment by lucianomcsilva** [comment] 2021-02-16 14:26
Hi. I just struggle this morning with this issue.  I have to install the lib myself. It take a long while. Use this command to do it

`brew install --build-from-source zstd`

Do it, and you can brew a coffee. It took more than 1 hour here. =)

**Comment by DMarby** [comment] 2021-03-05 16:05
@JCMais From a brief investigation, I believe this is due to the recent upgrade to libcurl 7.73.0 in https://github.com/JCMais/node-libcurl/commit/7ba328207185640b0ca58f490d76d211b40ac5d7, as libcurl added zstd support in `7.72.0`: https://daniel.haxx.se/blog/2020/08/19/curl-7-72-0-more-compression/

I believe passing `--without-zstd` to `./configure` in `build-libcurl.sh` would resolve it for now (with the trade-off of not having zstd support, until it can be statically built and included)., but I have not been able to verify that yet.

`otool` output of node-libcurl 2.30, showing the zstd dependency:
![image](https://user-images.githubusercontent.com/174626/110140773-bc435480-7dd4-11eb-9886-0ecc37aabfe7.png)

**Comment by JCMais** [comment] 2021-03-06 15:14
Thank you @DMarby, I still do not have access to a Mac to properly test this, but your findings were very useful to understand the root cause of the problem.

I'm pushing the above changes to try to get libcurl to link against the static version of zstd.

**Comment by DMarby** [comment] 2021-03-07 13:15
Thank you for the quick fix @JCMais!

I have verified that the new binaries from running `./build.sh` does not contain libzstd anymore:
![image](https://user-images.githubusercontent.com/174626/110240462-49f58000-7f4c-11eb-9a70-ed8156e333dd.png)
And when using the resulting build in Insomnia it seems to be working correctly now as well:
![image](https://user-images.githubusercontent.com/174626/110241120-72cb4480-7f4f-11eb-8468-f8f1993f8937.png)

Would it be possible to cut a new release with these changes, to get the prebuilt binaries working again?

**Comment by JCMais** [comment] 2021-03-07 15:58
Thanks for testing @DMarby.

I should be able to cut a new release in the next few days, about having the prebuilt binaries I'm waiting on TravisCI Support for that, macOS builds are run in there and it seems the OSS allowance for this repository is over the limit. 

In the meantime, I'm working on getting macOS builds also running on GitHub actions.

**Comment by DMarby** [comment] 2021-03-07 16:21
@JCMais Awesome, thanks a lot again, looking forward to it!

Please let me know if I can be of any assistance, or if you need any further help with MacOS testing or such.

**Comment by dr-dimitru** [comment] 2021-03-08 09:17
> Thanks for testing @DMarby.
> 
> I should be able to cut a new release in the next few days, about having the prebuilt binaries I'm waiting on TravisCI Support for that, macOS builds are run in there and it seems the OSS allowance for this repository is over the limit.
> 
> In the meantime, I'm working on getting macOS builds also running on GitHub actions.

Hey, we can have remote session from my mac if it would work for you

**Comment by JCMais** [comment] 2021-03-08 14:07
@dr-dimitru thanks for the suggestion, I will definitely keep that in mind for the future :)

I just released the pre-release version `v2.3.1-0` with the fixed `zstd` dependency. If anyone is able to test please let me know. If everything is working correctly I should be able to release `v2.3.1` tomorrow.

**Comment by DMarby** [comment] 2021-03-08 14:21
@JCMais More then happy to help test it!
It seems like the 9.3.3 Electron build failed due to some network errors, could I ask you to trigger a re-run of it, so that I'm able to test it with Electron 9? https://github.com/JCMais/node-libcurl/runs/2056979415?check_suite_focus=true

**Comment by JCMais** [comment] 2021-03-08 14:24
@DMarby re-running them now, unfortunately, there is no way to re-run just the failed jobs with GitHub Actions, so the whole workflow is running again.

**Comment by DMarby** [comment] 2021-03-08 14:25
@JCMais Thank you! Indeed, we have the same issue frequently, it is very unfortunate that you can't re-run just a single job 😅

**Comment by JCMais** [comment] 2021-03-08 15:27
@DMarby prebuilt binary for 9.3 is now available

**Comment by DMarby** [comment] 2021-03-08 16:05
Thank you @JCMais! I've tested it on macOS now, and it seems to be working great :)

**Comment by DMarby** [comment] 2021-03-08 18:18
Tested the electron build as linux as well @JCMais, and seems to work great there too 👍 
One thing I noticed is that for `node` the `glibc` binaries seem to be missing for the pre-release, will that be the case for the release as well, or is that just for the pre-release?

**Comment by JCMais** [comment] 2021-03-08 18:40
@DMarby the `glibc` builds are on TravisCI, I am awaiting a response from their support about my OSS allowance. Currently, it says I used all my credit (I did not even know this was a thing for OSS projects).

If I don't get this solved by the end of today/tomorrow, I will probably just use another CI provider to run the `glibc` builds, probably GitHub Actions as it seems to be the fastest one at the moment.

**Comment by JCMais** [comment] 2021-03-09 21:37
Closing this issue as `v2.3.1` has been released, full changelog [available here](https://github.com/JCMais/node-libcurl/releases/tag/v2.3.1).

It may take some time until all the prebuilt binaries are available.

**Closed by JCMais** 2021-03-09 21:37 UTC

**Comment by DMarby** [comment] 2021-03-09 21:40
Thank you for all your hard work on fixing this @JCMais!

**Comment by JCMais** [comment] 2021-03-09 21:56
Worth pointing out that zstd is not included by default in the Windows prebuilt binary, I will try to add it next week.
